### PR TITLE
Allow customization of the react output file

### PR DESCRIPTION
**Pull request by koddsson**
Hi 👋🏻 

I'd like to be able to set the output filename. Here's a quick change that allows for that. Let me know what you think 🙏🏻

### CODE REVIEW

**Comment by koddsson** [comment]
I just wrote this out but there's no tests so I'm not actually sure if this works or not :D

**Comment by break-stuff** [comment]
Are you trying to change the name of the file name of your wrapper? What you have here would change the name of the manifest file and I'm not sure that's what you're going for.

**Comment by break-stuff** [comment]
Also, you can test your changes if you run `npm run analyze`. You should see the output in the `demo` directory.

**Comment by break-stuff** [comment]
Were you still needing to try to customize your output file name?

**Comment by break-stuff** [comment]
Do you mind if I close this? I'm happy to help if you still need this in the future.

**Comment by break-stuff** [comment]
Closing due to inactivity.

**Pull request closed without merging**
